current_hour = int(input())
current_minute = int(input())
alarm_hour = int(input())
alarm_minute = int(input())
print('ALARM')
print()
alarm_time_hour = ((current_hour + alarm_hour) % 12) + int((current_minute + alarm_minute)/60)
alarm_time_minute = '{:02d}'.format((current_minute + alarm_minute) % 60)
print('Your alarm will go off at:')
print(str(alarm_time_hour) + ':' + str(alarm_time_minute))
print(f'in {alarm_hour} hours and {alarm_minute} minutes.')

